BaSP-MR-61: subscriptions add and divide components
BaSP-m2023/ferpa-megarocket-app pull request #32
Opened 2023-06-07 02:08 UTC by Dannylez

2023-06-08 01:53 UTC, DelfiLT requested changes
When you try to edit or add a suscription the app crashes.
For UI corrections you should add to the background image   `background-repeat: no-repeat;`
 ` background-position: center;`

2023-06-08 02:31 UTC, ukiweskamp commented
> When you try to edit or add a suscription the app crashes. For UI corrections you should add to the background image `background-repeat: no-repeat;` ` background-position: center;`

I haven't had a chance to test the code yet but Danny made changes to the server and did a merge. That's probably why it won't work for you.

2023-06-08 03:55 UTC, Bigzufi commented on src/Components/Layout/index.jsx
> +import Form from '../Subscriptions/Form';
You shouldn't use such a generic name like Form, try using SubscriptionForm or SubsForm.

2023-06-08 11:06 UTC, Dannylez commented
> When you try to edit or add a suscription the app crashes. For UI corrections you should add to the background image `background-repeat: no-repeat;` ` background-position: center;`

Fixed, it doesn't crash anymore, and for the background I've used "background-size: cover" now, I hope you like it

2023-06-08 12:27 UTC, DelfiLT approved these changes

2023-06-08 20:26 UTC, SantiH97 approved these changes
Overall the code seems pretty well implemented, its clean, I didn't find anything unnecessary or too hard to read. I will leave two suggestions regarding presentation:
1- I don't think you should be showing the deleted item's id on deletion as it provides no usefull information for the end user
2 - I there's no data to show, either because it isnt loading or because the isn't any, you get the same message, so theoretically you can be waiting for a very long time without ever knowing if the data is going to show or there simply isnt any.

2023-06-08 21:03 UTC, Dannylez commented
> Overall the code seems pretty well implemented, its clean, I didn't find anything unnecessary or too hard to read. I will leave two suggestions regarding presentation:
> 1- I don't think you should be showing the deleted item's id on deletion as it provides no usefull information for the end user
> 2 - I there's no data to show, either because it isnt loading or because the isn't any, you get the same message, so theoretically you can be waiting for a very long time without ever knowing if the data is going to show or there simply isnt any.

Ok, about the first point: I think it's something to fix from the server what include on the message when a deletion is made.
About the second point: I think you're right, maybe I can add a new state that returns true when the Get request is completed and customize the message either is still waiting a response or not

2023-06-08 21:33 UTC, ukiweskamp approved these changes

2023-06-09 01:01 UTC, merged

2023-06-09 01:02 UTC, Dannylez commented
![](https://github.trello.services/images/mini-trello-icon.png) [Subscription - Add and Divide Components](https://trello.com/c/6dOOaFmB/61-subscription-add-and-divide-components)