BaSP-MR-62: Trainers components added
BaSP-m2023/ferpa-megarocket-app pull request #35
Opened 2023-06-07 02:23 UTC by MatiasSauvanet

Features:

-Divide index in two components (Index and formTrainer)
-Still need some visuals 
-Added classmates components

2023-06-09 00:04 UTC, Bigzufi commented on src/Components/Trainers/FormTrainers/index.jsx
> +      return data;
Remove console.log

2023-06-09 00:04 UTC, Bigzufi commented on src/Components/Trainers/FormTrainers/index.jsx
> +        console.log(message);
Remove console.log

2023-06-09 00:05 UTC, Bigzufi commented on src/Components/Trainers/FormTrainers/index.jsx
> +    console.log(item);
Remove console.log

2023-06-09 00:05 UTC, Bigzufi commented on src/Components/Trainers/FormTrainers/index.jsx
> +      } else {
Remove console.log

2023-06-09 00:16 UTC, Bigzufi commented
The delete function is not working correctly. It doesn't delete the selected trainer but removes the last one from the list instead. The add trainer function is also not working properly. In case of a validation error, it still displays a success message, and the trainer is not created. Additionally, you should resolve conflicts.

2023-06-09 02:33 UTC, DelfiLT requested changes
Correct the changes requested and for the UI you could make the table a little bigger and add a padding to the blue box to look prettier, also, you should fix the font size from the table.

2023-06-09 02:33 UTC, DelfiLT commented on src/Components/Trainers/index.jsx
> +      alert(error);
Don't use alerts

2023-06-09 02:33 UTC, DelfiLT commented on src/Components/Trainers/FormTrainers/index.jsx
> +        throw message;
this isn't working, you should report this message on the modal

2023-06-09 02:33 UTC, DelfiLT commented on src/Components/Trainers/FormTrainers/index.jsx
> +        throw message;
Same here

2023-06-10 14:48 UTC, DelfiLT approved these changes

2023-06-10 14:48 UTC, Dannylez approved these changes

2023-06-10 15:10 UTC, merged