BaSP-MR-95: admins implement redux
BaSP-m2023/ferpa-megarocket-app pull request #52
Opened 2023-06-14 01:19 UTC by Bigzufi

2023-06-14 01:48 UTC, DelfiLT commented on src/Components/Admins/index.jsx
> +  console.log(error);
Remove console.log

2023-06-14 16:54 UTC, SantiH97 requested changes
-DELETE and GET work as expected. Good work on those.
-On edit: the error message is displayed on the table and not on the form, the success message has the same issue and displays "deleted admin" instead of "updated admin". On a successful update it doesnt redirect you at all, you should pass history.push('/admins'); on a successful update. cosider adding  "success: false" on the INITIAL_STATE of your reducer and changing its value accordingly
-on add: Upon a succesful registration the form does not redirect you or display any modals, as in the previous issue an error is only shown in the table and not the form. Adding that success bolean could help you here as well.
Delete unnecessary commented code, after you finish and before you merge.

2023-06-15 00:16 UTC, Bigzufi commented on src/Components/Admins/index.jsx
> +  console.log(error);
Done!

2023-06-15 01:37 UTC, DelfiLT approved these changes

2023-06-15 21:33 UTC, SantiH97 approved these changes

2023-06-15 22:57 UTC, merged