BaSP-MR-91: Superadmin Implement REDUX
BaSP-m2023/ferpa-megarocket-app pull request #54
Opened 2023-06-14 02:17 UTC by ukiweskamp

2023-06-14 03:13 UTC, ukiweskamp commented
![](https://github.trello.services/images/mini-trello-icon.png) [SuperAdmins - Implement redux](https://trello.com/c/3D3ktxQl/98-superadmins-implement-redux)

2023-06-14 17:09 UTC, SantiH97 requested changes
Uppon a successful deletion the delete modal is not closed and therefore it allow you to delete an allready deleted member.
success messages are not shown on the success modal

2023-06-14 22:48 UTC, ukiweskamp commented
> Uppon a successful deletion the delete modal is not closed and therefore it allow you to delete an allready deleted member. success messages are not shown on the success modal

The PR was in WIP precisely because it needed to fix messages and modals.
Thanks for the feedback, if you try now everything should be working!

2023-06-15 00:33 UTC, Bigzufi commented on src/Components/SuperAdmins/index.jsx
> +    console.log(message);
Remove console.log

2023-06-15 00:34 UTC, Bigzufi commented on src/Components/SuperAdmins/index.jsx
> +  }, [dispatch]);
dispatch is a constant (function), it doesn't make sense to be listed as a dependency because it doesn't change state

2023-06-15 00:36 UTC, Bigzufi commented on src/redux/superadmins/thunks.js
> +      dispatch(actions.getSuperadminsSuccess(data.data));
You can destructure data as { data, message }, instead of data.data or data.message

2023-06-15 00:36 UTC, Bigzufi commented on src/redux/superadmins/thunks.js
> +      dispatch(actions.postSuperadminsSuccess(data.data, data.message));
You can destructure data as { data, message }, instead of data.data or data.message

2023-06-15 00:37 UTC, Bigzufi commented on src/redux/superadmins/thunks.js
> +      dispatch(actions.putSuperadminsSuccess(id, data.data, data.message));
You can destructure data as { data, message }, instead of data.data or data.message

2023-06-15 02:00 UTC, DelfiLT requested changes

2023-06-15 14:45 UTC, Milicerro reviewed
Everything seems functional and matches the UX/UI

2023-06-15 21:32 UTC, SantiH97 approved these changes
Well done :)

2023-06-15 22:42 UTC, Bigzufi approved these changes
Well done!

2023-06-15 22:44 UTC, merged