Basp-MR-96: Add remaining redux methods
BaSP-m2023/ferpa-megarocket-app pull request #55
Opened 2023-06-14 11:58 UTC by SantiH97

Added the following redux fetch methods
-POST
-PUT
-DELETE

Added CSS fixes

2023-06-15 02:13 UTC, DelfiLT requested changes
Functionallity:
The success modals aren't working

UX/UI:
For the delete modal you should use the warning modal, and the delete button should be red, you should use the delete button

2023-06-15 02:13 UTC, DelfiLT commented on src/Components/Classes/Form/index.jsx
> +import { getActivities } from '../../../redux/activities/thunks';
You have 3 different imports from thunks, use one

2023-06-15 02:13 UTC, DelfiLT commented on src/Components/Classes/Form/index.jsx
> +import { useDispatch } from 'react-redux';
You have 2 different imports from react redux, use one

2023-06-15 02:13 UTC, DelfiLT commented on src/Components/Classes/Form/index.jsx
>            {showSuccessModal && (
The success modal it's not working, you have to use it when it redirects you in the index

2023-06-15 02:13 UTC, DelfiLT commented on src/redux/classes/actions.js
> +import {
For a suggestion you could use import * to not call one by one

2023-06-15 17:55 UTC, DelfiLT approved these changes

2023-06-15 22:41 UTC, Bigzufi approved these changes
Good Job!!

2023-06-15 22:48 UTC, merged

2023-06-16 14:04 UTC, SantiH97 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Classes - Fix- Delete modal and error handling](https://trello.com/c/8Nema4C0/103-classes-fix-delete-modal-and-error-handling)