BaSP-MR43:
BaSP-m2023/ferpa-megarocket-app pull request #6
Opened 2023-05-31 02:10 UTC by MatiasSauvanet

Pendent to finish the edit part, have some problems with GetByIdMember.

2023-05-31 02:33 UTC, DelfiLT commented on package-lock.json
remove package-lock.json from your changes

2023-05-31 02:33 UTC, DelfiLT commented on src/Components/Members/index.js
> +      console.log(error);
Change all of these for change.error

2023-05-31 02:33 UTC, DelfiLT commented on src/Components/Members/index.js
> +      console.error(error);
Same here

2023-05-31 02:33 UTC, DelfiLT commented on src/Components/Members/index.js
> +      console.error(error);
Same here

2023-05-31 02:33 UTC, DelfiLT commented on src/Components/Members/index.js
> +  // const [memberFormValue, setMemberFormValue] = useState({
In the final commit remember to delete the comments

2023-05-31 21:17 UTC, SantiH97 submitted a review, later dismissed
Change those and you should be good to go

2023-05-31 21:17 UTC, SantiH97 commented on src/Components/Members/index.js
> +      console.error;
same here

2023-05-31 21:17 UTC, SantiH97 commented on src/Components/Members/index.js
> +      console.error;
same here

2023-05-31 23:38 UTC, SantiH97 commented on src/Components/Members/index.js
> +    console.log(member);
Delete unnecessary console.log

2023-06-01 00:46 UTC, Dannylez commented on src/Components/Members/index.js
> +      console.log(error);
Do you mean "console.error"?

2023-06-01 00:47 UTC, Dannylez requested changes
remove package-lock.json from your changes

2023-06-01 03:04 UTC, DelfiLT commented on src/Components/Members/index.js
> +      console.log(error);
Yes sorry

2023-06-01 20:19 UTC, DelfiLT approved these changes

2023-06-01 20:22 UTC, Dannylez approved these changes

2023-06-02 00:38 UTC, DelfiLT commented on src/Components/Members/index.js
> +    console.log(member);
Delete console.log

2023-06-02 01:07 UTC, Juanoauil approved these changes

2023-06-02 02:42 UTC, merged